# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  A survey of the tools and techniques of computation as applied to concepts
  in humanities. Covers the use of computing to analyze and synthesize
  textual, visual, and aural data, as well as the creation of new digital
  artifacts using computation. Topics normally include natural language
  processing and translation, information retrieval, sentiment analysis,
  document clustering, data visualization, procedural music generation,
  and digital art. Prerequisite: CSCI 150
baseurl: "/csci270" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

number: CSCI 270
title: Computational Humanities
semester: Spring 2022

navigation:
  - title: Overview
    subfolderitems:
      - page: Description
        url: '#description'
      - page: Learning Goals
        url: '#goals'
      - page: Resources
        url: '#resources'
  - page: Readings
    url: '#readings'
  - page: In-Class Code
    url: '#inclasscode'
  - page: Calendar
    url: 'https://app.teamgantt.com/public/projects/calendar/2020-01-12?ids=1990087&projectIds=1990087&publicKeys=eh0JCy4TSjrP&userResourceIds=0'
  - title: Coursework
    subfolderitems:
      - page: Labs
        url: '#labs'
      - page: Project
        url: '#projects'
      - page: Exams
        url: '#exams'
      - page: Checkins
        url: '#checkins'
      - page: Scale
        url: '#scale'
  - page: Commitments
    url: '#commitments'

instructors:
  - id: yorgey
    name: Dr. Brent Yorgey
    email: yorgey@hendrix.edu
    web: http://ozark.hendrix.edu/~yorgey
    phone: (501) 450-1377
    officehours: https://byorgey.youcanbook.me
  - id: goadrich
    name: Dr. Mark Goadrich
    email: goadrich@hendrix.edu
    web: http://mark.goadrich.com
    phone: (501) 450-1367
    officehours: http://mark.goadrich.com/schedule.html
  - id: ferrer
    name: Dr. Gabriel Ferrer
    email: ferrer@hendrix.edu
    web: http://ozark.hendrix.edu/~ferrer
    phone: (501) 450-3879
    officehours: https://drferrer.youcanbook.me/
  - id: seme
    name: Prof. Lars Seme
    email: seme@hendrix.edu
    web: https://www.hendrix.edu/mathcs/profile.aspx?id=70795
    phone: (501) 450-1256
    officehours: ???

offerings:
  - name: LECTURE 01
    loc: MCREY 315
    time: MWF 11:10am - 12:00pm
    instructor: ferrer

resources:
  - name: Python 3
    image: assets/images/pythonlogo.png
    url: http://python.org
  - name: Kaggle Kernels
    image: assets/images/kaggle.png
    url: https://www.kaggle.com/kernels
  - name: Calligraphr
    image: assets/images/calligraphr.jpg
    url: https://www.calligraphr.com/en/
  - name: Sonic Pi
    image: assets/images/sonicpi.png
    url: https://sonic-pi.net/
  - name: Graphviz
    image: assets/images/graphviz.png
    url: https://www.graphviz.org/
  - name: Context Free Art
    image: assets/images/context_free_art.png
    url: https://www.contextfreeart.org/
  - name: Ren'Py
    image: assets/images/renpy.png
    url: https://www.renpy.org/
  - name: MuseScore
    image: assets/images/musescore.png
    url: https://musescore.com/
  - name: Anaconda
    image: assets/images/anaconda.png
    url: https://www.anaconda.com/distribution/

extra-resources:
  - name: "How to Think Like a Computer Scientist: Interactive Edition"
    image: assets/images/runestone_logo.png
    url: https://runestone.academy/runestone/books/published/thinkcspy/index.html
  - name: Python Tutor
    image: assets/images/python_tutor.png
    url: http://pythontutor.com/
  - name: CodingBat Python
    image: assets/images/codingbat.jpg
    url: https://codingbat.com/python
  - name: CheckiO Python Practice
    image: assets/images/checkio_logo_small.png
    url: https://py.checkio.org/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
